In [2]:
from limpieza_ventas import df_ventas
from limpieza_horas import df_horas
from limpieza_casos import df_casos

(1427, 19)
Fecha de Inicio          datetime64[us]
Horas Inicio                      Int64
Cuenta                              str
Título                              str
Estado Pip.                         str
Fecha de Cierre          datetime64[us]
Hora de cierre                    Int64
Nº                                int64
Tipo de origen                      str
Origen                              str
Id del origen                   float64
Departamento / Equipo               str
Asignado a                          str
Asignado por                        str
Duración                          Int64
Estado                              str
Contacto                            str
cant_tiempos                      int64
id_tiempos                       object
dtype: object
    Fecha de Inicio  Horas Inicio                               Cuenta  \
330      2026-05-31           385  Lomas de City Bell - Barrio Privado
331      2026-05-30           861                          Irma Marino
332      2026-05-30          1073                          Estadio Uno
333      2026-05-30           829  Lomas de City Bell - Barrio Privado
334      2026-05-29          1042                    Silvia Casagrande

                                                Título Estado Pip.  \
330  INFORME SEMANAL DE SISTEMA DE GRABACIONES 31/0...  Finalizado
331  Revisar y emprolijar cables de las cámaras al DVR    Cobrados
332                         Inconvenientes con cámaras  Finalizado
333                          Equipos del Market caídos  Finalizado
334                    Cotizacion de impresora | Color     Enviada

    Fecha de Cierre  Hora de cierre     Nº Tipo de origen  \
330      2026-06-01             712  16597         Cuenta
331      2026-06-17            1121  16596         Cuenta
332      2026-06-08             736  16595         Cuenta
333      2026-06-01             741  16594       Contrato
334             NaT            <NA>  16593         Cuenta

                                                Origen  Id del origen  \
330                Lomas de City Bell - Barrio Privado         8717.0
331                                        Irma Marino         8392.0
332                                        Estadio Uno         8854.0
333  Mantenimiento CCTV - 2 visitas mensuales de 4 ...           46.0
334                                  Silvia Casagrande         8921.0

    Departamento / Equipo         Asignado a        Asignado por  Duración  \
330       Infraestructura    Leandro caselli              Airbot         0
331       Infraestructura       Luis cuadro      Soporte - Local        60
332       Infraestructura       Luis cuadro      Soporte - Local       200
333       Departamento IT  Agustin Gonzalez      Soporte - Local       520
334                   NaN    Soporte - Local  Agustina Plazzotta         0

      Estado           Contacto  cant_tiempos                    id_tiempos
330  Cerrado  Guardia City Bell             0                            []
331  Cerrado        Irma Marino             1                       [20705]
332  Cerrado            Claudia             4  [20744, 20708, 20704, 20668]
333  Cerrado                NaN             2                [20677, 20675]
334  Abierto  Silvia Casagrande             0                            []

In [13]:
df_casos[df_casos["Nº"] == 16594]

,Fecha de Inicio,Horas Inicio,Cuenta,Título,Estado Pip.,Fecha de Cierre,Hora de cierre,Nº,Tipo de origen,Origen,Id del origen,Departamento / Equipo,Asignado a,Asignado por,Duración,Estado,Contacto,cant_tiempos,id_tiempos
333,2026-05-30,829,Lomas de City Bell - Barrio Privado,Equipos del Market caídos,Finalizado,2026-06-01,741,16594,Contrato,Mantenimiento CCTV - 2 visitas mensuales de 4 ...,46.0,Departamento IT,Agustin Gonzalez,Soporte - Local,520,Cerrado,NaN,2,"[20677, 20675]"

In [ ]:
df_horas[df_horas["Tipo de fuente"].str.contains("Contrato:",na=False)

,Nº,Fecha de Inicio,Fecha de Finalización,Tipo de fuente,Origen,Cuenta,Usuario,Duración,Donde,Tipo de Intervención,Reporte de Cuenta,Fecha de Creación,Estado inicial del origen,id_caso
517,20677,2026-05-30 09:00:00,2026-05-30 13:50:00,Caso,Caso: Equipos del Market caídos - Nº: 16594,Lomas de City Bell - Barrio Privado,Agustin Gonzalez,290,Ubicación,Intervención técnica,"Estábamos en el market, tenemos 1 antena que e...",2026-06-01 12:20:00,Clientes de Mantenimiento:Pendiente,16594
518,20675,2026-05-30 09:00:00,2026-05-30 12:50:00,Caso,Caso: Equipos del Market caídos - Nº: 16594,Lomas de City Bell - Barrio Privado,Sanchez Nicolas,230,Ubicación,Intervención técnica,El caso lo realiza Agus.\n,2026-06-01 12:11:00,Clientes de Mantenimiento:Pendiente,16594
519,20665,2026-05-30 12:00:00,2026-05-30 12:45:00,Contrato,Contrato: Mantenimiento mensual sitio web Bats...,Batsa,Virginia Ramos,45,Remoto,Diseño web,"Actualización Joomla 5.4.6, Akeeba 10.3.3, Yoo...",2026-05-30 12:45:00,Web/Redes Sociales:Abierto,5
520,20662,2026-05-30 11:00:00,2026-05-30 12:00:00,Contrato,Contrato: Mantenimiento mensual sitio web - Nº: 4,Espacio Educativo Jacaranda S.R.L,Virginia Ramos,60,Remoto,Diseño web,Recibo el reporte del Antimalware de Nuthost c...,2026-05-30 12:01:00,Web/Redes Sociales:Abierto,4
521,20696,2026-05-30 11:00:00,2026-05-30 12:00:00,Caso,Caso: Su equipo no reconoce el disco - Nº: 16592,Bell Motors,Agustina Plazzotta,60,Ubicación,Soporte,Se verifico el estado del disco externamente y...,2026-06-02 15:17:00,Clientes de Mantenimiento:Pendiente,16592
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2502,18676,2026-01-02 11:54:00,2026-01-02 12:01:00,Caso,Caso: Se desconfiguraron unidades de red - Nº:...,Hidroar S.A,Gunther Barcelone,7,Remoto,Soporte,Se mapearon las unidades del servidor\n,2026-01-02 15:07:00,Clientes de Mantenimiento:Pendiente,15165
2503,18678,2026-01-02 11:38:00,2026-01-02 11:50:00,Caso,Caso: Corregir mail de Juan Brandi - Nº: 15164,Zíngaro Multimarca,Gunther Barcelone,12,Remoto,Soporte,Se creo el correo juan.brandi y se borro el qu...,2026-01-02 15:37:00,Clientes de Mantenimiento:Pendiente,15164
2504,18677,2026-01-02 09:52:00,2026-01-02 11:40:00,Caso,Caso: Impresora sin conexión - Nº: 15163,GIUVI S.A (KIA),Gunther Barcelone,108,Remoto,Soporte,Se configuro correctamente la impresora en los...,2026-01-02 15:09:00,Clientes de Mantenimiento:Pendiente,15163
2505,18700,2026-01-02 10:00:00,2026-01-02 10:30:00,Caso,Caso: Inconvenientes luego de corte de luz - N...,Vicente Zíngaro VW,Leandro caselli,30,Ubicación,Intervención técnica,Se deja provisoriamente conectado los dos rack...,2026-01-05 10:56:00,Clientes de Mantenimiento:Pendiente,15168
2506,18679,2026-01-02 08:29:00,2026-01-02 09:26:00,Caso,Caso: Perdió el acceso directo a Autológica - ...,Bell Motors,Gunther Barcelone,57,Remoto,Soporte,"Se encontró el servidor apagado fisicamente, s...",2026-01-02 15:40:00,Clientes de Mantenimiento:Pendiente,15161

In [5]:


# Suponiendo que tus datos los cargás en un DataFrame llamado 'df'
# df = pd.read_csv('tu_archivo.csv') o pd.read_excel('tu_archivo.xlsx')

# Agrupar por la columna 'Asignado a'
analisis = df_casos.groupby('Asignado a').agg(
    total_duracion=('Duración', 'sum'),
    cantidad_casos=('Asignado a', 'count')
).reset_index()

# Ordenar para ver quién tuvo MÁS duración en total
top_duracion = analisis.sort_values(by='total_duracion', ascending=False)
print("--- Ranking por mayor duración ---")
print(top_duracion)

# Ordenar para ver quién tuvo MÁS casos asignados
top_casos = analisis.sort_values(by='cantidad_casos', ascending=False)
print("\n--- Ranking por mayor cantidad de casos ---")
print(top_casos)

--- Ranking por mayor duración ---
                Asignado a  total_duracion  cantidad_casos
5             Luis cuadro            37763             147
4          Leandro caselli           32312             154
2        Gunther Barcelone           19266             546
0        Agustin Gonzalez            12079              28
8          Sanchez Nicolas           11481               9
1       Agustina Plazzotta           10844             254
7    Ramiro Martínez Conte            5458             208
3             Jimena Ojeda            2550              20
10          Virginia Ramos            2203              20
6   Paulo Suarez Algardata            1255              11
9          Soporte - Local             165               9
11        fernando caselli              20              21

--- Ranking por mayor cantidad de casos ---
                Asignado a  total_duracion  cantidad_casos
2        Gunther Barcelone           19266             546
1       Agustina Plazzotta           10844             254
7    Ramiro Martínez Conte            5458             208
4          Leandro caselli           32312             154
5             Luis cuadro            37763             147
0        Agustin Gonzalez            12079              28
11        fernando caselli              20              21
3             Jimena Ojeda            2550              20
10          Virginia Ramos            2203              20
6   Paulo Suarez Algardata            1255              11
8          Sanchez Nicolas           11481               9
9          Soporte - Local             165               9